{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example",
    "module": "customtransformplugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.0.0.jar",
          "url": "customtransformplugin-1.0.0.jar",
          "size": 25107,
          "sha512": "da0941e11b69f120ab3ef5ef35b67302e4737b91546ab9531d9642703f22ea1397198303de907097eb1d241e3c2f961a52b9c638edd752aae1ff6b12ff257790",
          "sha256": "97c4db68ab4cc8ae2e7d0887408a75b17be3a9d1e011b03d81829a865d886b64",
          "sha1": "f56d3a4192b2eb0e37bb11d7b4ab06860fabf4d1",
          "md5": "6e3d19492990275b1d5c3d24d09524f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.0.0.jar",
          "url": "customtransformplugin-1.0.0.jar",
          "size": 25107,
          "sha512": "da0941e11b69f120ab3ef5ef35b67302e4737b91546ab9531d9642703f22ea1397198303de907097eb1d241e3c2f961a52b9c638edd752aae1ff6b12ff257790",
          "sha256": "97c4db68ab4cc8ae2e7d0887408a75b17be3a9d1e011b03d81829a865d886b64",
          "sha1": "f56d3a4192b2eb0e37bb11d7b4ab06860fabf4d1",
          "md5": "6e3d19492990275b1d5c3d24d09524f1"
        }
      ]
    }
  ]
}
