{
  "formatVersion": "1.1",
  "component": {
    "group": "AndroidTest",
    "module": "plugintest",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugintest-unspecified.jar",
          "url": "plugintest-unspecified.jar",
          "size": 31587,
          "sha512": "9462a6fa413bbdcf5eaee8d71351c4272bed4c5d5e819efa6986b74d551d33b62747829f8091821b180d808e2c740e6f479c66108b2b875d1a63732c0ea96d01",
          "sha256": "7ba901e90c95c9a1ed1d36d1786bae01180e6fd14f17131e72b20934b54e8878",
          "sha1": "1899b95f9529916f9ab4fb5e054e8cd64bf70432",
          "md5": "0f79c61f5d22d605bb58ddc58078b81e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugintest-unspecified.jar",
          "url": "plugintest-unspecified.jar",
          "size": 31587,
          "sha512": "9462a6fa413bbdcf5eaee8d71351c4272bed4c5d5e819efa6986b74d551d33b62747829f8091821b180d808e2c740e6f479c66108b2b875d1a63732c0ea96d01",
          "sha256": "7ba901e90c95c9a1ed1d36d1786bae01180e6fd14f17131e72b20934b54e8878",
          "sha1": "1899b95f9529916f9ab4fb5e054e8cd64bf70432",
          "md5": "0f79c61f5d22d605bb58ddc58078b81e"
        }
      ]
    }
  ]
}
