{
  "formatVersion": "1.1",
  "component": {
    "group": "AndroidTest",
    "module": "plugintest",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugintest-unspecified.jar",
          "url": "plugintest-unspecified.jar",
          "size": 31593,
          "sha512": "444b81f79656fb0bcd34b9490c06ef4ac983e9b520fccb0dbd72fc849eaf6694e869d35f5549762c3bc44100fd78d74cda943c98830d5e091bed2be30de5a930",
          "sha256": "316e2aa3175d8ec9885720a9d8494fd6d71c2757b6c50b3072e90cc3539eaf6d",
          "sha1": "54ddcbb704a66cb1f10652995a558a7a210ec31b",
          "md5": "f7de5b874e5443197633b1304eabb12b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugintest-unspecified.jar",
          "url": "plugintest-unspecified.jar",
          "size": 31593,
          "sha512": "444b81f79656fb0bcd34b9490c06ef4ac983e9b520fccb0dbd72fc849eaf6694e869d35f5549762c3bc44100fd78d74cda943c98830d5e091bed2be30de5a930",
          "sha256": "316e2aa3175d8ec9885720a9d8494fd6d71c2757b6c50b3072e90cc3539eaf6d",
          "sha1": "54ddcbb704a66cb1f10652995a558a7a210ec31b",
          "md5": "f7de5b874e5443197633b1304eabb12b"
        }
      ]
    }
  ]
}
