package com.example.administrator.androidtest.Test.MainTest.OptTest.BootOptTest;

public class ClassPreloadExecutor {

    private static String[] initClassNameList = new String[] {
            "com.bumptech.glide.load.engine.bitmap_recycle.LruBitmapPool",
            "com.example.administrator.androidtest.Widget.FullTextView.FullTextView",
            "com.bear.libcomponent.component.ComponentAct",
            "com.example.administrator.androidtest.Widget.LoopViewPager.LoopViewPager",
            "kotlin.sequences.SequencesKt",
            "androidx.appcompat.widget.AppCompatTextView",
            "com.bear.libcomponent.base.BaseAct",
            "com.facebook.drawee.view.SimpleDraweeView",
            "kotlin.sequences.SequencesKt___SequencesKt",
            "androidx.appcompat.widget.AppCompatCheckBox",
            "com.alibaba.android.arouter.facade.template.IInterceptorGroup",
            "androidx.constraintlayout.widget.ConstraintLayout",
            "androidx.appcompat.widget.ActionBarContextView",
            "androidx.appcompat.widget.Toolbar",
            "com.example.administrator.androidtest.R$styleable",
            "com.example.administrator.androidtest.Test.MainTest.MainAct",
            "androidx.appcompat.widget.AppCompatAutoCompleteTextView",
            "androidx.constraintlayout.solver.widgets.ConstraintWidgetContainer",
            "androidx.appcompat.widget.AppCompatButton",
            "kotlin.sequences.SequencesKt___SequencesJvmKt",
            "com.example.administrator.androidtest.Test.MainTest.BottomSheetTest.VpAndRvBottomSheetFragment",
            "androidx.appcompat.app.AppCompatActivity",
            "androidx.viewpager.widget.ViewPager",
            "com.example.administrator.androidtest.Widget.InputView",
            "kotlin.collections.MapsKt",
            "androidx.appcompat.widget.FitWindowsLinearLayout",
            "org.aspectj.runtime.reflect.MethodSignatureImpl",
            "androidx.appcompat.widget.AppCompatImageButton",
            "com.facebook.drawee.view.GenericDraweeView",
            "androidx.appcompat.widget.AppCompatEditText",
            "androidx.appcompat.widget.AppCompatSpinner",
            "kotlin.sequences.SequencesKt__SequencesKt",
            "com.example.administrator.androidtest.Widget.MoreTextView",
            "androidx.fragment.app.BackStackRecord",
            "com.example.administrator.androidtest.Widget.FlowLayout",
            "androidx.appcompat.widget.AppCompatCheckedTextView",
            "com.google.android.material.bottomsheet.BottomSheetDialogFragment",
            "androidx.collection.MapCollections$EntrySet",
            "com.example.administrator.androidtest.Widget.MarqueeTextView",
            "androidx.appcompat.view.menu.ListMenuPresenter",
            "com.facebook.drawee.backends.pipeline.PipelineDraweeController",
            "com.bumptech.glide.request.target.BitmapImageViewTarget",
            "com.facebook.imagepipeline.core.ImagePipelineExperiments",
            "androidx.appcompat.widget.AppCompatMultiAutoCompleteTextView",
            "org.aspectj.lang.reflect.MethodSignature",
            "com.example.administrator.androidtest.Test.MainTest.OtherTest.OtherTestComponent",
            "androidx.constraintlayout.widget.R$styleable",
            "androidx.core.view.LayoutInflaterCompat$Factory2Wrapper",
            "androidx.appcompat.app.AppCompatDelegateImpl",
            "com.example.administrator.androidtest.Widget.ShadowLayout",
            "androidx.appcompat.widget.AppCompatRadioButton",
            "kotlin.collections.MapsKt___MapsKt",
            "com.example.administrator.androidtest.Widget.FlowFakeTextView",
            "com.example.administrator.androidtest.Test.MainTest.CaseViewTest.Case.CaseView",
            "kotlin.sequences.SequencesKt__SequencesJVMKt",
            "leakcanary.internal.HeapDumpControl$ICanHazHeap$Yup",
            "kotlin.collections.ArraysKt___ArraysKt$groupingBy$1",
            "androidx.fragment.app.FragmentContainerView",
            "androidx.constraintlayout.solver.widgets.Barrier",
            "org.aspectj.runtime.reflect.CodeSignatureImpl",
            "com.bumptech.glide.load.engine.Engine",
            "androidx.constraintlayout.solver.widgets.WidgetContainer",
            "com.example.administrator.androidtest.Test.MainTest.BackgroundService",
            "com.example.administrator.androidtest.Test.MainTest.CoordinatorLayoutTest.CoordinatorLayoutTestAct",
            "com.bumptech.glide.request.target.ImageViewTarget",
            "androidx.appcompat.app.AppCompatDialogFragment",
            "androidx.appcompat.view.SupportActionModeWrapper$CallbackWrapper",
            "androidx.constraintlayout.widget.Constraints",
            "com.facebook.drawee.view.DraweeView",
            "com.facebook.common.executors.DefaultSerialExecutorService",
            "androidx.appcompat.app.AppCompatDelegateImpl$ListMenuDecorView",
            "kotlin.collections.MapsKt___MapsJvmKt",
            "kotlin.collections.SetsKt",
            "androidx.appcompat.graphics.drawable.DrawableWrapper",
            "androidx.appcompat.widget.AppCompatImageView",
            "com.facebook.drawee.controller.AbstractDraweeController",
            "androidx.appcompat.widget.ContentFrameLayout",
            "androidx.appcompat.widget.AppCompatSeekBar",
            "com.example.administrator.androidtest.Test.MainTest.ViewGetSizeTest.ViewGetSizeTestAct",
            "androidx.appcompat.widget.AppCompatRatingBar",
            "com.facebook.imagepipeline.datasource.CloseableProducerToDataSourceAdapter",
            "com.facebook.common.executors.UiThreadImmediateExecutorService",
            "androidx.core.graphics.TypefaceCompatApi29Impl",
            "org.aspectj.runtime.reflect.JoinPointImpl$EnclosingStaticPartImpl",
            "com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilder",
            "androidx.vectordrawable.graphics.drawable.VectorDrawableCompat",
            "com.example.administrator.androidtest.Test.MainTest.TestComponent",
            "com.example.administrator.androidtest.Test.MainTest.FragTest.FragLifecycleTestAct",
            "com.example.administrator.androidtest.Widget.FullTextView.FullTextView$1",
            "androidx.appcompat.widget.AbsActionBarView",
            "com.example.administrator.androidtest.Test.MainTest.ToolbarTest.ToolbarTestAct",
            "org.aspectj.lang.reflect.CodeSignature",
            "org.aspectj.runtime.reflect.FieldSignatureImpl",
            "com.example.administrator.androidtest.Widget.LikeView.LikeView",
            "com.example.administrator.androidtest.Test.MainTest.FloatServiceTest.TestFloatService",
            "com.facebook.fresco.animation.bitmap.BitmapAnimationBackend",
            "androidx.core.graphics.TypefaceCompatApi28Impl",
            "com.example.libfresco.FrescoUtil$5",
            "com.bumptech.glide.load.engine.cache.MemorySizeCalculator",
            "androidx.constraintlayout.solver.widgets.analyzer.WidgetRun",
            "androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener",
            "androidx.core.graphics.drawable.WrappedDrawable",
            "com.bumptech.glide.load.resource.gif.GifDrawable",
            "com.bumptech.glide.RequestBuilder",
            "org.aspectj.lang.NoAspectBoundException",
            "com.facebook.imagepipeline.memory.BufferMemoryChunkPool",
            "kotlin.random.Random$Default",
            "com.bear.libcomponent.component.ComponentFrag",
            "com.facebook.fresco.animation.drawable.AnimatedDrawable2",
            "androidx.constraintlayout.widget.VirtualLayout",
            "androidx.appcompat.widget.TintResources",
            "kotlin.collections.CollectionsKt__IterablesKt$Iterable$1",
            "kotlin.collections.MapsKt__MapsKt",
            "androidx.appcompat.widget.AppCompatTextViewAutoSizeHelper$Impl29",
            "com.bumptech.glide.RequestManager",
            "androidx.appcompat.view.menu.MenuBuilder",
            "androidx.arch.core.internal.FastSafeIterableMap",
            "org.aspectj.runtime.reflect.JoinPointImpl",
            "androidx.fragment.app.FragmentActivity$HostCallbacks",
            "org.aspectj.runtime.reflect.MemberSignatureImpl",
            "com.example.administrator.androidtest.Test.MainTest.CoordinatorLayoutTest.BehaviorTestAct",
            "androidx.constraintlayout.widget.Placeholder",
            "org.aspectj.runtime.reflect.CatchClauseSignatureImpl",
            "com.bumptech.glide.module.AppGlideModule",
            "kotlin.comparisons.ComparisonsKt__ComparisonsKt$compareBy$2",
            "androidx.constraintlayout.widget.ConstraintHelper",
            "androidx.fragment.app.DialogFragment",
            "androidx.constraintlayout.widget.Guideline",
            "androidx.appcompat.app.WindowDecorActionBar",
            "com.example.administrator.androidtest.Test.MainTest.ShareTest.SystemShareAct",
            "com.bear.libcomponent.component.ComponentService$PageComponentStack",
            "androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback",
            "androidx.constraintlayout.solver.widgets.HelperWidget",
            "curtains.internal.WindowCallbackWrapper",
            "org.aspectj.runtime.internal.AroundClosure",
            "kotlin.collections.SetsKt___SetsKt",
            "com.facebook.common.executors.HandlerExecutorServiceImpl",
            "org.aspectj.runtime.reflect.InitializerSignatureImpl",
            "com.facebook.imagepipeline.cache.CountingMemoryCache",
            "androidx.appcompat.app.AppCompatDelegateImpl$PanelMenuPresenterCallback",
            "com.example.administrator.androidtest.Widget.InputView$ClearAction",
            "com.example.administrator.androidtest.Test.MainTest.DialogTest.TestDialog",
            "androidx.savedstate.Recreator",
            "com.facebook.imagepipeline.datasource.AbstractProducerToDataSourceAdapter",
            "com.example.administrator.androidtest.Test.MainTest.MotionTest.MotionTestAct",
            "androidx.constraintlayout.solver.widgets.ConstraintWidget",
            "com.bear.libcomponent.component.BaseComponent",
            "androidx.appcompat.app.AppCompatDelegateImpl$7",
            "androidx.core.content.res.ResourcesCompat$FontCallback",
            "com.example.administrator.androidtest.Test.MainTest.CaseViewTest.Case.LoadingCaseInfo",
            "com.tencent.mmkv.MMKV",
            "com.facebook.imagepipeline.request.ImageRequest",
            "com.example.administrator.androidtest.Widget.LikeView.LikeView$1",
            "com.example.administrator.androidtest.Test.MainTest.MainAct$1",
            "androidx.core.R$id",
            "androidx.arch.core.internal.SafeIterableMap$DescendingIterator",
            "androidx.core.view.LayoutInflaterFactory",
            "com.facebook.common.memory.ByteArrayPool",
            "androidx.appcompat.R$styleable",
            "java.util.StringTokenizer",
            "com.example.administrator.androidtest.Test.MainTest.KVCompareTest.KVCompareTestAct",
            "com.bear.libcomponent.component.FragmentComponent",
            "androidx.appcompat.widget.AppCompatToggleButton",
            "androidx.appcompat.widget.TintContextWrapper",
            "androidx.viewpager.widget.ViewPager$1",
            "androidx.collection.ArrayMap",
            "com.example.administrator.androidtest.Test.MainTest.AspectTest.AspectTestAct",
            "kotlin.collections.AbstractList$Companion",
            "curtains.WindowsKt$tooltipString$2",
            "androidx.core.util.Pools$SynchronizedPool",
            "com.facebook.common.internal.Suppliers$2",
            "androidx.constraintlayout.solver.SolverVariable$1",
            "com.facebook.imagepipeline.datasource.BaseBitmapDataSubscriber",
            "androidx.constraintlayout.solver.ArrayRow",
            "org.aspectj.runtime.reflect.ConstructorSignatureImpl",
            "androidx.appcompat.app.ToolbarActionBar",
            "androidx.lifecycle.LifecycleService",
            "com.bumptech.glide.request.target.ViewTarget",
            "androidx.core.view.ViewCompat$5",
            "com.example.administrator.androidtest.Test.MainTest.ScreenTest.ScreenAct",
            "androidx.appcompat.widget.ViewStubCompat",
            "org.aspectj.lang.reflect.MemberSignature",
            "androidx.appcompat.widget.ViewStubCompat$OnInflateListener",
            "com.bear.libkv.SpVal.SpVal",
            "org.aspectj.runtime.reflect.UnlockSignatureImpl",
            "androidx.appcompat.app.ActionBar",
            "androidx.arch.core.internal.SafeIterableMap$IteratorWithAdditions",
            "leakcanary.internal.ViewModelClearedWatcher$Companion$install$provider$1",
            "org.aspectj.runtime.reflect.AdviceSignatureImpl",
            "com.facebook.imagepipeline.producers.ThreadHandoffProducerQueue",
            "com.facebook.drawee.controller.AbstractDraweeControllerBuilder",
            "org.aspectj.runtime.reflect.LockSignatureImpl",
            "com.facebook.imagepipeline.producers.HttpUrlConnectionNetworkFetcher$2",
            "com.example.administrator.androidtest.Test.MainTest.ARouterTest.Module1Provider",
            "com.example.administrator.androidtest.Test.MainTest.ViewPager2Test.ViewPager2Act",
            "com.facebook.imagepipeline.image.CloseableImage",
            "androidx.fragment.app.FragmentManager$LifecycleAwareResultListener",
            "androidx.collection.ArraySet",
            "androidx.collection.SimpleArrayMap",
            "com.facebook.imagepipeline.platform.OreoDecoder",
            "com.example.administrator.androidtest.Widget.OverLinkMovementMethod",
            "androidx.core.view.accessibility.AccessibilityNodeInfoCompat",
            "androidx.fragment.app.FragmentManager$2",
            "com.bumptech.glide.load.engine.EngineJob",
            "androidx.constraintlayout.widget.ConstraintLayout$Measurer",
            "com.bumptech.glide.load.resource.bitmap.BitmapEncoder",
            "com.example.libbase.Util.XmlDrawableUtil$1",
            "androidx.arch.core.executor.ArchTaskExecutor",
            "com.facebook.imagepipeline.memory.MemoryPooledByteBufferOutputStream",
            "androidx.constraintlayout.widget.ConstraintSet",
            "androidx.activity.ComponentActivity$6",
            "com.bumptech.glide.request.target.PreloadTarget",
            "com.facebook.drawee.generic.GenericDraweeHierarchy",
            "com.example.libbase.Util.ToastUtil",
            "com.facebook.imagepipeline.listener.RequestListener",
            "androidx.core.graphics.TypefaceCompatApi26Impl",
            "com.facebook.soloader.UnpackingSoSource$Dso",
            "androidx.core.app.TaskStackBuilder",
            "androidx.viewpager.widget.ViewPager$SavedState",
            "com.bumptech.glide.Glide",
            "com.facebook.soloader.SysUtil$LollipopSysdeps",
            "com.bumptech.glide.RequestManager$ClearTarget",
            "com.example.administrator.androidtest.Test.MainTest.BottomViewTest.RvBottomView",
            "androidx.appcompat.widget.AppCompatBackgroundHelper",
            "org.aspectj.runtime.reflect.Factory",
            "com.facebook.common.executors.ScheduledFutureImpl",
            "androidx.fragment.app.LogWriter",
            "androidx.constraintlayout.solver.Cache",
            "com.facebook.imagepipeline.memory.MemoryChunkPool",
            "com.facebook.cache.disk.DefaultEntryEvictionComparatorSupplier$1",
            "androidx.appcompat.app.AppCompatDialog",
            "com.alibaba.android.arouter.facade.Postcard",
            "androidx.constraintlayout.solver.widgets.analyzer.ChainRun",
            "androidx.constraintlayout.solver.widgets.VirtualLayout",
            "com.example.administrator.androidtest.Widget.FloatService",
            "androidx.appcompat.widget.AppCompatTextViewAutoSizeHelper",
            "com.bumptech.glide.load.resource.bitmap.DefaultImageHeaderParser",
            "com.facebook.soloader.MinElf",
            "com.facebook.imagepipeline.producers.SettableProducerContext",
            "com.facebook.imagepipeline.producers.HttpUrlConnectionNetworkFetcher",
            "androidx.core.text.PrecomputedTextCompat",
            "com.facebook.fresco.animation.backend.AnimationBackendDelegateWithInactivityCheck",
            "androidx.constraintlayout.solver.widgets.Guideline",
            "com.facebook.drawee.view.DraweeHolder",
            "androidx.activity.ComponentActivity$7",
            "androidx.appcompat.widget.AppCompatImageHelper",
            "com.bumptech.glide.load.engine.cache.LruResourceCache",
            "androidx.appcompat.widget.ResourceManagerInternal$ColorFilterLruCache",
            "kotlin.collections.ArraysKt___ArraysKt$asIterable$$inlined$Iterable$2",
            "androidx.vectordrawable.graphics.drawable.VectorDrawableCommon",
            "androidx.core.view.ViewCompat$AccessibilityPaneVisibilityManager",
            "androidx.collection.MapCollections$KeySet",
            "androidx.fragment.app.FragmentManager$7",
            "com.example.libfresco.Listener.LogControllListener",
            "com.facebook.imagepipeline.decoder.SimpleProgressiveJpegConfig$DefaultDynamicValueConfig",
            "com.bear.libcomponent.base.BaseFrag",
            "kotlin.collections.MapsKt__MapsJVMKt",
            "com.bumptech.glide.request.SingleRequest",
            "androidx.appcompat.widget.AppCompatTextViewAutoSizeHelper$Impl23",
            "kotlin.collections.SetsKt__SetsKt",
            "com.bumptech.glide.load.engine.Engine$EngineJobFactory$1",
            "com.facebook.imagepipeline.producers.LocalFileFetchProducer",
            "com.facebook.soloader.UnpackingSoSource$InputDso",
            "curtains.WindowsKt$onDecorViewReady$$inlined$run$lambda$1",
            "com.alibaba.android.arouter.base.UniqueKeyTreeMap",
            "androidx.lifecycle.ReportFragment",
            "com.facebook.imagepipeline.image.CloseableStaticBitmap",
            "com.facebook.soloader.ApkSoSource",
            "com.google.android.material.appbar.AppBarLayout$OnOffsetChangedListener",
            "com.facebook.soloader.UnpackingSoSource",
            "androidx.fragment.app.FragmentManager$6",
            "androidx.appcompat.app.AppCompatDelegateImpl$3",
            "androidx.appcompat.app.AppCompatDelegateImpl$5",
            "androidx.appcompat.app.AppCompatDelegateImpl$AutoBatteryNightModeManager",
            "com.bumptech.glide.load.engine.bitmap_recycle.LruArrayPool",
            "com.facebook.imagepipeline.cache.BitmapCountingMemoryCacheFactory$1",
            "androidx.core.content.res.ResourcesCompat$FontCallback$2",
            "kotlin.UInt",
            "androidx.core.graphics.TypefaceCompatBaseImpl$2",
            "com.facebook.imagepipeline.cache.BitmapMemoryCacheFactory$1",
            "androidx.collection.MapCollections$ValuesCollection",
            "androidx.core.widget.TintableCompoundButton",
            "com.facebook.imagepipeline.cache.BitmapMemoryCacheKey",
            "com.bumptech.glide.load.engine.ActiveResources$2",
            "com.bumptech.glide.load.engine.DecodeJob",
            "androidx.appcompat.widget.AppCompatDrawableManager$1",
            "androidx.constraintlayout.solver.LinearSystem",
            "androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure",
            "com.example.administrator.androidtest.Test.MainTest.RecyclerViewTest.RecyclerViewTestComponent$1",
            "androidx.appcompat.widget.ResourcesWrapper",
            "com.bumptech.glide.load.resource.bitmap.CenterCrop",
            "com.example.administrator.androidtest.Widget.FullTextView.FullTextView$2",
            "androidx.core.view.ViewCompat$2",
            "com.facebook.cache.disk.FileCache",
            "com.effective.android.anchors.AnchorsManager$Companion",
            "androidx.core.view.ViewCompat",
            "androidx.appcompat.app.AppCompatDelegate",
            "org.aspectj.lang.reflect.FieldSignature",
            "com.facebook.imagepipeline.platform.GingerbreadPurgeableDecoder",
            "com.bumptech.glide.load.engine.cache.MemorySizeCalculator$DisplayMetricsScreenDimensions",
    };

    public static void doPreload() {
        ClassLoader classLoader = ClassPreloadExecutor.class.getClassLoader();
        try {
            for (String className : initClassNameList) {
                Class.forName(className, true, classLoader);
            }
        } catch (Exception e) {

        }
        initClassNameList = null;
    }
}

/*
效果不是特别明显，需要大型项目来验证。
---------------------------- Test 1 ----------------------------
2023-11-22 19:25:48.953  6429-6429  BootTaskManager         com...ple.administrator.androidtest  I  logColdStartUp: cold start
2023-11-22 19:25:49.007  6429-6429  AndroidTestApplication  com...ple.administrator.androidtest  I  onCreate: enter
2023-11-22 19:25:49.140  6429-6429  BootTaskManager         com...ple.administrator.androidtest  I  logColdEndUp: cold end, duration = 187
2023-11-22 19:25:49.140  6429-6429  BootTaskManager         com...ple.administrator.androidtest  I  logWarmStartUp: warm start
2023-11-22 19:25:49.335  6429-6429  MainAct                 com...ple.administrator.androidtest  I  onCreate: enter
2023-11-22 19:25:49.609  6429-6429  ViewRootImpl[MainAct]   com...ple.administrator.androidtest  D  windowFocusChanged hasFocus=true inTouchMode=true
2023-11-22 19:25:49.610  6429-6429  BootTaskManager         com...ple.administrator.androidtest  I  logWarmEndUp: warm end, duration = 470

2023-11-22 19:27:22.826  6433-6433  BootTaskManager         com...ple.administrator.androidtest  I  logColdStartUp: cold start
2023-11-22 19:27:22.882  6433-6433  AndroidTestApplication  com...ple.administrator.androidtest  I  onCreate: enter
2023-11-22 19:27:23.017  6433-6433  BootTaskManager         com...ple.administrator.androidtest  I  logColdEndUp: cold end, duration = 192
2023-11-22 19:27:23.018  6433-6433  BootTaskManager         com...ple.administrator.androidtest  I  logWarmStartUp: warm start
2023-11-22 19:27:23.214  6433-6433  MainAct                 com...ple.administrator.androidtest  I  onCreate: enter
2023-11-22 19:27:23.492  6433-6433  ViewRootImpl[MainAct]   com...ple.administrator.androidtest  D  windowFocusChanged hasFocus=true inTouchMode=true
2023-11-22 19:27:23.492  6433-6433  BootTaskManager         com...ple.administrator.androidtest  I  logWarmEndUp: warm end, duration = 474
---------------------------- Test 1 ----------------------------

---------------------------- Test 2 ----------------------------
2023-11-22 20:14:47.930 14903-14903 BootTaskManager         com...ple.administrator.androidtest  I  logColdEndUp: cold end, duration = 165
2023-11-22 20:14:47.930 14903-14903 BootTaskManager         com...ple.administrator.androidtest  I  logWarmStartUp: warm start
2023-11-22 20:14:48.126 14903-14903 MainAct                 com...ple.administrator.androidtest  I  onCreate: enter
2023-11-22 20:14:48.397 14903-14903 ViewRootImpl[MainAct]   com...ple.administrator.androidtest  D  windowFocusChanged hasFocus=true inTouchMode=true
2023-11-22 20:14:48.397 14903-14903 BootTaskManager         com...ple.administrator.androidtest  I  logWarmEndUp: warm end, duration = 467

2023-11-22 20:15:39.318 14904-14904 BootTaskManager         com...ple.administrator.androidtest  I  logColdEndUp: cold end, duration = 165
2023-11-22 20:15:39.318 14904-19980 BootTaskManager         com...ple.administrator.androidtest  D  onRelease: AnchorDPTask
2023-11-22 20:15:39.318 14904-14904 BootTaskManager         com...ple.administrator.androidtest  I  logWarmStartUp: warm start
2023-11-22 20:15:39.515 14904-14904 MainAct                 com...ple.administrator.androidtest  I  onCreate: enter
2023-11-22 20:15:39.791 14904-14904 ViewRootImpl[MainAct]   com...ple.administrator.androidtest  D  windowFocusChanged hasFocus=true inTouchMode=true
2023-11-22 20:15:39.791 14904-14904 BootTaskManager         com...ple.administrator.androidtest  I  logWarmEndUp: warm end, duration = 473
---------------------------- Test 2 ----------------------------

---------------------------- Test 3 ----------------------------
2023-11-22 20:18:08.029 14905-14905 BootTaskManager         com...ple.administrator.androidtest  I  logColdEndUp: cold end, duration = 257
2023-11-22 20:18:08.029 14905-14905 BootTaskManager         com...ple.administrator.androidtest  I  logWarmStartUp: warm start
2023-11-22 20:18:08.029 14905-20604 BootTaskManager         com...ple.administrator.androidtest  D  onRelease: AnchorDPOptTask
2023-11-22 20:18:08.173 14905-14905 MainAct                 com...ple.administrator.androidtest  I  onCreate: enter
2023-11-22 20:18:08.421 14905-14905 ViewRootImpl[MainAct]   com...ple.administrator.androidtest  D  windowFocusChanged hasFocus=true inTouchMode=true
2023-11-22 20:18:08.422 14905-14905 BootTaskManager         com...ple.administrator.androidtest  I  logWarmEndUp: warm end, duration = 393

2023-11-22 20:18:53.541 14906-14906 BootTaskManager         com...ple.administrator.androidtest  I  logColdEndUp: cold end, duration = 272
2023-11-22 20:18:53.541 14906-20789 BootTaskManager         com...ple.administrator.androidtest  D  onRelease: AnchorDPOptTask
2023-11-22 20:18:53.541 14906-14906 BootTaskManager         com...ple.administrator.androidtest  I  logWarmStartUp: warm start
2023-11-22 20:18:53.687 14906-14906 MainAct                 com...ple.administrator.androidtest  I  onCreate: enter
2023-11-22 20:18:53.932 14906-14906 ViewRootImpl[MainAct]   com...ple.administrator.androidtest  D  windowFocusChanged hasFocus=true inTouchMode=true
2023-11-22 20:18:53.940 14906-14906 BootTaskManager         com...ple.administrator.androidtest  I  logWarmEndUp: warm end, duration = 398
---------------------------- Test 3 ----------------------------
 */
