{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example",
    "module": "customtransformplugin",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.0.3.jar",
          "url": "customtransformplugin-1.0.3.jar",
          "size": 31590,
          "sha512": "c9ea4c78bf9a4682fccd571d7da1df1fd8744f68676b3c8d172b72e4ced56f80b942e6c3a4582cfd4549a25ea49ab5971d64531f67ca8da4d018fd5ff3ea58eb",
          "sha256": "8e2e4c9d96fee391c676895cb5b76a1ad0feff9d8982c375c8724057c184a10c",
          "sha1": "76b4bca31ff908c9805300f3049ca91a7ba64dcc",
          "md5": "46404fdb92d14d2c83ae2761d01153b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.0.3.jar",
          "url": "customtransformplugin-1.0.3.jar",
          "size": 31590,
          "sha512": "c9ea4c78bf9a4682fccd571d7da1df1fd8744f68676b3c8d172b72e4ced56f80b942e6c3a4582cfd4549a25ea49ab5971d64531f67ca8da4d018fd5ff3ea58eb",
          "sha256": "8e2e4c9d96fee391c676895cb5b76a1ad0feff9d8982c375c8724057c184a10c",
          "sha1": "76b4bca31ff908c9805300f3049ca91a7ba64dcc",
          "md5": "46404fdb92d14d2c83ae2761d01153b7"
        }
      ]
    }
  ]
}
