{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example",
    "module": "customtransformplugin",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.0.2.jar",
          "url": "customtransformplugin-1.0.2.jar",
          "size": 31602,
          "sha512": "98e5f049694b709adb900896cc86e8909dde02809fbe5b90c0e8af7204b34c104bd8e7e06852049150fc663c43b7d765af0b85c5a73c5c9d9742637fe8926313",
          "sha256": "2ccc2d7df389b99006f7604d213c161d62f8137d382586ff17d034952c329eb9",
          "sha1": "af238acc56b9da099d1714ec366d4e1f4bfb642f",
          "md5": "e06533d61922f55d23e02ce357b28b6f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.0.2.jar",
          "url": "customtransformplugin-1.0.2.jar",
          "size": 31602,
          "sha512": "98e5f049694b709adb900896cc86e8909dde02809fbe5b90c0e8af7204b34c104bd8e7e06852049150fc663c43b7d765af0b85c5a73c5c9d9742637fe8926313",
          "sha256": "2ccc2d7df389b99006f7604d213c161d62f8137d382586ff17d034952c329eb9",
          "sha1": "af238acc56b9da099d1714ec366d4e1f4bfb642f",
          "md5": "e06533d61922f55d23e02ce357b28b6f"
        }
      ]
    }
  ]
}
