{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example",
    "module": "customtransformplugin",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.0.1.jar",
          "url": "customtransformplugin-1.0.1.jar",
          "size": 31591,
          "sha512": "2e5b99a92aec1908f516dff2e5d4ca09eab677e8dcf0595f13960f917dc8ed81b9240f4b35c119bb80b497bbd4124961263acb25dcb46b388c6cae86e89c377a",
          "sha256": "251464b74552a5ffb2d008c00523217fe34eaa429fcf980623eefcda833ee96e",
          "sha1": "c5fee4d40b66fb6cf8b07d514c09bece5a334d3c",
          "md5": "a599321691a09b7290224973d6f35507"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.0.1.jar",
          "url": "customtransformplugin-1.0.1.jar",
          "size": 31591,
          "sha512": "2e5b99a92aec1908f516dff2e5d4ca09eab677e8dcf0595f13960f917dc8ed81b9240f4b35c119bb80b497bbd4124961263acb25dcb46b388c6cae86e89c377a",
          "sha256": "251464b74552a5ffb2d008c00523217fe34eaa429fcf980623eefcda833ee96e",
          "sha1": "c5fee4d40b66fb6cf8b07d514c09bece5a334d3c",
          "md5": "a599321691a09b7290224973d6f35507"
        }
      ]
    }
  ]
}
