{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example",
    "module": "customtransformplugin",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.0.1.jar",
          "url": "customtransformplugin-1.0.1.jar",
          "size": 31461,
          "sha512": "7a6b51dbe1a4522ea68c6a6d6b319b2e9d9c2073eb43bc3b5c5c3962b83d7a842ff120916bb327ddfc6e5e9c4fec2f5d84070eda246fa80c9962a8743193c346",
          "sha256": "1ebf920c29bb670db448b53c1d080d205604037bedbd489c12663cb4f58b38df",
          "sha1": "9012eaeff6f909df9bba7a83851428ac03ef85ce",
          "md5": "4db165a50fc90dd526eac0cd6a55c7af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.0.1.jar",
          "url": "customtransformplugin-1.0.1.jar",
          "size": 31461,
          "sha512": "7a6b51dbe1a4522ea68c6a6d6b319b2e9d9c2073eb43bc3b5c5c3962b83d7a842ff120916bb327ddfc6e5e9c4fec2f5d84070eda246fa80c9962a8743193c346",
          "sha256": "1ebf920c29bb670db448b53c1d080d205604037bedbd489c12663cb4f58b38df",
          "sha1": "9012eaeff6f909df9bba7a83851428ac03ef85ce",
          "md5": "4db165a50fc90dd526eac0cd6a55c7af"
        }
      ]
    }
  ]
}
