{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example",
    "module": "customtransformplugin",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.0.1.jar",
          "url": "customtransformplugin-1.0.1.jar",
          "size": 31602,
          "sha512": "70c46d43fa97fe0735cab9444b3a72c949ca72a6c733b6eb2627de2bcaa7b23d3f230da741a34fc0ca9920177e30ecdd35be09b035be9f631deb3cef7774f508",
          "sha256": "9979e30efc2f332d0155769fedf8d611271a9a2d93e35aa0d0fe3761404194c0",
          "sha1": "fad8c13cfb4ecaa3eb04252018d6cc76471ad0fe",
          "md5": "b5c34e3bac8b937c6ab06fd23067e29f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.0.1.jar",
          "url": "customtransformplugin-1.0.1.jar",
          "size": 31602,
          "sha512": "70c46d43fa97fe0735cab9444b3a72c949ca72a6c733b6eb2627de2bcaa7b23d3f230da741a34fc0ca9920177e30ecdd35be09b035be9f631deb3cef7774f508",
          "sha256": "9979e30efc2f332d0155769fedf8d611271a9a2d93e35aa0d0fe3761404194c0",
          "sha1": "fad8c13cfb4ecaa3eb04252018d6cc76471ad0fe",
          "md5": "b5c34e3bac8b937c6ab06fd23067e29f"
        }
      ]
    }
  ]
}
